services:
  mongo:
    image: mongo:noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gehenna

  backend:
    build: ./backend
    environment:
      MONGO_URL: mongodb://admin:password123@mongo:27017/gehenna?authSource=admin
      PORT: 8002
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    networks:
      - gehenna

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: http://backend:8002
      PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - backend
    networks:
      - gehenna

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongo
    networks:
      - gehenna

volumes:
  mongo_data:

networks:
  gehenna:
    driver: bridge
