kind: ConfigMap
apiVersion: v1
metadata:
  name: gehenna-config
  namespace: {{ .Values.namespace }}
data:
  ##FRONTEND
  BACKEND_URL: "http://gehenna-backend.{{ .Values.namespace }}.svc.cluster.local:8002"
  FRONTEND_PORT: "8001"
  ##BACKEND
  BACKEND_PORT: "8002"
  ##MONGO
  MONGO_HOST: "mongo"
  MONGO_HOST_FULL: "mongo.{{ .Values.namespace }}.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "gehenna"
  