kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: gehenna-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gehenna-frontend
              port:
                number: 8001
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: gehenna-backend
              port:
                number: 8002
        - path: /mongo-express
          pathType: Prefix
          backend:
            service:
              name: mongo-express
              port:
                number: 8081