apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: {{ .Values.mongoexpressImage }}
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: gehenna-config
        - secretRef:
            name: gehenna-secrets
        env:
        - name: ME_CONFIG_SITE_BASEURL
          value: "/mongo-express"
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: gehenna-config
              key: MONGO_HOST
        - name: ME_CONFIG_MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: gehenna-config
              key: MONGO_PORT
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: gehenna-secrets
              key: MONGO_USERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: gehenna-secrets
              key: MONGO_PASSWORD
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: gehenna-secrets
              key: MONGO_USERNAME
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gehenna-secrets
              key: MONGO_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP

