apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gehenna
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NamanSondhiya/Project-Gehenna.git
    targetRevision: Tram
    path: gehenna-chart
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: avaline # match the namespace with the one in values.yaml for consistency or any errors
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
