namespace: gehenna
frontendImage: docker.io/namanss/gehenna-frontend-ii:latest
backendImage: docker.io/namanss/gehenna-backend-ii:latest
mongoexpressImage: docker.io/mongo-express:1.0.2-20-alpine3.19
mongoImage: docker.io/mongo:noble