@Library("jenkins-shared") _
pipeline {
    agent any

    parameters {
        string(name: 'IMAGE_TAG_F', defaultValue: '', description: 'Frontend Docker image tag after CI build')
        string(name: 'IMAGE_TAG_B', defaultValue: '', description: 'Backend Docker image tag after CI build')
    }

    environment {
        EMAIL="ssnaman4@gmail.com"
    }

    stages {
        stage('Clean Workplace') {
            steps {
                script {
                    clean_ws()
                }
            }
        }
        stage('Code Clone') {
            steps {
                script {
                    git_clone("https://github.com/NamanSondhiya/Project_Gehenna.git", "devOps")
                }
            }
        }
        stage('Verify Docker Image Tags') {
            steps {
                script {
                    echo "IMAGE_TAG_F: ${params.IMAGE_TAG_F}"
                    echo "IMAGE_TAG_B: ${params.IMAGE_TAG_B}"
                }
            }
        }
        stage('Update the K8s manifest values.yaml') {
            steps {
                script {
                    sh """
                        sed -i "s|frontendImage: docker.io/namanss/gehenna-frontend-ii:.*|frontendImage: docker.io/namanss/gehenna-frontend-ii:${params.IMAGE_TAG_F}|" kubernetes/values.yaml

                        sed -i "s|backendImage: docker.io/namanss/gehenna-backend-ii:.*|backendImage: docker.io/namanss/gehenna-backend-ii:${params.IMAGE_TAG_B}|" kubernetes/values.yaml
                    """
                }
            }
        }
        stage('Git Code Update and Push to Github') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                    sh '''
                        git status
                        git config --global user.email "ssnaman4@gmail.com"
                        git config --global user.name "$GIT_USER"
                        
                        git add .
                        git status

                        git commit -m "Updated values.yaml via CD-JOB" || echo "No changes to commit"

                        echo "Pushing changes to github"
                        git push https://$GIT_USER:$GIT_PASS@github.com/NamanSondhiya/Project_Gehenna.git devOps
                    '''
                }
            }
        }
    }
    post {
        success {
            script {
                email_success("${EMAIL}")
            }

        }
        failure {
            script {
                email_failure("${EMAIL}")
            }
        }
    }
}